name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a82e6ff7fdfa65d96180dac02eaaea4d5d3db9b9b3fbba4c1d031c29b91e18d4"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
