name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05c34ec3ef69319f8955563fe91facab208bcbaf7a80773c073441a1bb7d18de"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
