name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2645258fbe0ccd1ea7ace380d95cac8a4d2d7592191bcab62448127f27aaed2"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
