name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "190bbdc918b9e7a848d1ef0d13546dc20ba00e65d6901bae5123691faf926dfd"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
