name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a0fc13b2538b45c1242e18c6a2678c20f1573b42bbdb1d6a65458f9144614e0"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
