name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.1.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a5f0631b491ac191e76afd739b98bcdf923ecc9bcc80ccf7d95b6bb505be700"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
