name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.1.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7862425e45305c40a2f9b2ffd53d3cc174c1a7c73d25e8234bdefac09bad3877"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
