name = "The Trax Pack"
author = "AMTraxTGE"
version = "0.1.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24c2737494661159e41423f62cc129eb8a06c816058ada40678aea698505dadd"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
