name: Trax Pack Workflow

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate Trax Pack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v0.9.13

      - name: Setup GO Language
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19' 
      
      - name: Install PackWiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Generate MultiMC Instance
        run: |
          cd multimc
          zip -r ../TheTraxPack-MultiMC-${{ env.GitVersion_SemVer }}.zip *
          cd ..

      - name: Generate Modrinth Pack
        run: |
          cd pack
          packwiz mr export -o ../TheTraxPack-${{ env.GitVersion_SemVer }}.mrpack

      - name: Upload Modrinth Pack
        uses: actions/upload-artifact@v3
        with:
          name: TheTraxPack-Modrinth-${{ env.GitVersion_SemVer }}
          path: TheTraxPack-${{ env.GitVersion_SemVer }}.mrpack

      - name: Upload MultiMC Instance
        uses: actions/upload-artifact@v3
        with:
          name: TheTraxPack-MultiMC-${{ env.GitVersion_SemVer }}
          path: multimc/