name: Trax Pack Development

on:
  push:
    branches:
      - develop

jobs:
  generate:
    name: Generate Trax Pack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v0.9.13

      - name: Setup GO Language
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19' 
      
      - name: Install PackWiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Generate MultiMC Instance
        run: |
          zip TheTraxPack-MultiMC-${{ env.GitVersion_SemVer }}.zip multimc

      - name: Generate Modrinth Pack
        run: |
          cd client
          packwiz mr export -o TheTraxPack-${{ env.GitVersion_SemVer }}.mrpack

      - name: Publish Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.GitVersion_SemVer }}
          tag_name: ${{ env.GitVersion_SemVer }}
          files: |
            client/TheTraxPack-${{ env.GitVersion_SemVer }}.mrpack
            TheTraxPack-MultiMC-${{ env.GitVersion_SemVer }}.zip